---
title: "CheriseTrotman's Website"
author: "Cherise Trotman"
date: "12/02/2022"
output:
  html_document:
    theme: spacelab
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

Cherise is a young professional with a background in international development, trade and climate change projects. With over a decade spent between Barbados, Canada and Trinidad & Tobago,she has embraced working in diverse spaces and honed skills in project management, management and research. She holds a BA Hons. in International Studies &Economics (York University,Toronto) and a Msc. in International Trade Policy (UWI Cave Hill, Barbados). She speaks English and professional Spanish.

.

## Interests

* International Trade
* Innovation
* Caribbean Data Storytelling

## Projects

* List some of your recent projects
* You could include this website as a project!

## Profiles 

* [LinkedIn](https://www.linkedin.com/in/cherisetrotman/)
* [GitHub](http://github.com/CheriseTrotman)

## Contact

* [cherisetrotman@gmail.com](mailto:cherisetrotman@gmail.com)
